# Generated by Django 6.0.3 on 2026-03-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('$', 'US Dollar ($)'), ('৳', 'Bangladeshi Taka (৳)'), ('€', 'Euro (€)'), ('£', 'British Pound (£)'), ('₹', 'Indian Rupee (₹)'), ('¥', 'Japanese Yen (¥)'), ('C$', 'Canadian Dollar (C$)')], default='$', max_length=5)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
